// DO NOT EDIT THIS FILE
// Copyright (c) 2005, Borland Software Corporation. All Rights Reserved.
// version 3

package com.borland.jbcl.model;

public class Res extends java.util.ResourceBundle {

  protected Object handleGetObject(String key) { return null; }
  public java.util.Enumeration getKeys()       { return null; }

  private static final Res bundle = getBundle();

  private static Res getBundle() {
    try {
      return (Res)getBundle("com.borland.jbcl.model.Res");
    } catch (Exception e) {
      return new Res();
    }
  }

//------------------------------------------//
  protected    String _res_TreeNode2 = "Tree node {0} already contains sibling {1}";
  public static final String  _TreeNode2 = bundle._res_TreeNode2;
  protected    String _res_NoVariableColumns = "This model does not support variable columns";
  public static final String  _NoVariableColumns = bundle._res_NoVariableColumns;
  protected    String _res_NoModelSet = "A model must be set before calling this method";
  public static final String  _NoModelSet = bundle._res_NoModelSet;
  protected    String _res_TreeNode4 = "Tree node {0} not linked to parent {1}";
  public static final String  _TreeNode4 = bundle._res_TreeNode4;
  protected    String _res_TreeNode1 = "Tree node {0} is already a child of {1}";
  public static final String  _TreeNode1 = bundle._res_TreeNode1;
  protected    String _res_Error = "Error";
  public static final String  _Error = bundle._res_Error;
  protected    String _res_CantAdd = "Can''t add {0} to {1} : it''s already a child of {2}";
  public static final String  _CantAdd = bundle._res_CantAdd;
  protected    String _res_TreeCircularity = "Tree circularity in children of {0} after {1}";
  public static final String  _TreeCircularity = bundle._res_TreeCircularity;
  protected    String _res_TreeNode3 = "Tree node {0} is not a child of {1}";
  public static final String  _TreeNode3 = bundle._res_TreeNode3;
  protected    String _res_TreeNode = "Tree node {0} already contains child {1}";
  public static final String  _TreeNode = bundle._res_TreeNode;
  protected    String _res_NoVariableRows = "This model does not support variable rows";
  public static final String  _NoVariableRows = bundle._res_NoVariableRows;
//==========================================//

  public static String findString(String id) {
    try {
      return (String)Res.class.getDeclaredField("_" + id).get(null);
    } catch (Exception any) {
      return null;
    }
  }
}
