// DO NOT EDIT THIS FILE
// Copyright (c) 2005, Borland Software Corporation. All Rights Reserved.
// version 3

package com.borland.jbcl.model;

public class Res_de extends Res {
  public Res_de() {
    _res_TreeNode2 = "Baumknoten {0} enth\u00e4lt bereits gleichgeordnetes Element {1}";
    _res_NoVariableColumns = "Dieses Modell unterst\u00fctzt keine variablen Spalten";
    _res_NoModelSet = "Vor dem Aufruf dieser Methode muss ein Modell festgelegt werden.";
    _res_TreeNode4 = "Baumknoten {0} ist nicht mit \u00fcbergeordnetem Element {1} verkn\u00fcpft";
    _res_TreeNode1 = "Baumknoten {0} ist bereits untergeordnetes Element von {1}";
    _res_Error = "Fehler";
    _res_CantAdd = "{0} kann nicht zu {1} hinzugef\u00fcgt werden: es ist bereits {2} untergeordnet";
    _res_TreeCircularity = "Zirkul\u00e4re Verweise in untergeordneten Elementen von {0} nach {1}";
    _res_TreeNode3 = "Baumknoten {0} ist kein untergeordnetes Element von {1}";
    _res_TreeNode = "Baumknoten {0} enth\u00e4lt bereits untergeordnetes Element {1}";
    _res_NoVariableRows = "Dieses Modell unterst\u00fctzt keine variablen Zeilen";
  }
}
