// DO NOT EDIT THIS FILE
// Copyright (c) 2005, Borland Software Corporation. All Rights Reserved.
// version 3

package com.borland.jbcl.control;

public class Res extends java.util.ResourceBundle {

  protected Object handleGetObject(String key) { return null; }
  public java.util.Enumeration getKeys()       { return null; }

  private static final Res bundle = getBundle();

  private static Res getBundle() {
    try {
      return (Res)getBundle("com.borland.jbcl.control.Res");
    } catch (Exception e) {
      return new Res();
    }
  }

//------------------------------------------//
  protected    String _res_MenuText = "MenuText";
  public static final String  _MenuText = bundle._res_MenuText;
  protected    String _res_First = "First";
  public static final String  _First = bundle._res_First;
  protected    String _res_PostChanges = "Post Row Changes";
  public static final String  _PostChanges = bundle._res_PostChanges;
  protected    String _res_Hue = "Hue:";
  public static final String  _Hue = bundle._res_Hue;
  protected    String _res_Italic = "Italic";
  public static final String  _Italic = bundle._res_Italic;
  protected    String _res_Help = "Help";
  public static final String  _Help = bundle._res_Help;
  protected    String _res_FileNotFound = "Could not find file: {0}";
  public static final String  _FileNotFound = bundle._res_FileNotFound;
  protected    String _res_Brightness = "Brightness:";
  public static final String  _Brightness = bundle._res_Brightness;
  protected    String _res_Delete = "Delete";
  public static final String  _Delete = bundle._res_Delete;
  protected    String _res_AlignTop = "Top";
  public static final String  _AlignTop = bundle._res_AlignTop;
  protected    String _res_Save = "Save";
  public static final String  _Save = bundle._res_Save;
  protected    String _res_ControlShadow = "ControlShadow";
  public static final String  _ControlShadow = bundle._res_ControlShadow;
  protected    String _res_Cancel = "Cancel";
  public static final String  _Cancel = bundle._res_Cancel;
  protected    String _res_ToggleSort = "Toggle Sort Order";
  public static final String  _ToggleSort = bundle._res_ToggleSort;
  protected    String _res_Yes1 = "Yes";
  public static final String  _Yes1 = bundle._res_Yes1;
  protected    String _res_Insert = "Insert";
  public static final String  _Insert = bundle._res_Insert;
  protected    String _res_Highlight = "Highlight";
  public static final String  _Highlight = bundle._res_Highlight;
  protected    String _res_InvalidButtons = "Invalid button(s) {0}";
  public static final String  _InvalidButtons = bundle._res_InvalidButtons;
  protected    String _res_GridPopupTitle = "{0} (row {1})";
  public static final String  _GridPopupTitle = bundle._res_GridPopupTitle;
  protected    String _res_Last = "Last";
  public static final String  _Last = bundle._res_Last;
  protected    String _res_Ditto = "Ditto";
  public static final String  _Ditto = bundle._res_Ditto;
  protected    String _res_InactiveCaptionText = "InactiveCaptionText";
  public static final String  _InactiveCaptionText = bundle._res_InactiveCaptionText;
  protected    String _res_Info = "Info";
  public static final String  _Info = bundle._res_Info;
  protected    String _res_ReadOnlySet = "Component's readOnly property is set.";
  public static final String  _ReadOnlySet = bundle._res_ReadOnlySet;
  protected    String _res_Black = "Black";
  public static final String  _Black = bundle._res_Black;
  protected    String _res_AlignVStretch = "VStretch";
  public static final String  _AlignVStretch = bundle._res_AlignVStretch;
  protected    String _res_ActiveCaption = "ActiveCaption";
  public static final String  _ActiveCaption = bundle._res_ActiveCaption;
  protected    String _res_TextText = "TextText";
  public static final String  _TextText = bundle._res_TextText;
  protected    String _res_InactiveText = "InactiveText";
  public static final String  _InactiveText = bundle._res_InactiveText;
  protected    String _res_FontSample = "aAbBcCdDeEfFgGhH";
  public static final String  _FontSample = bundle._res_FontSample;
  protected    String _res_Saturation = "Saturation:";
  public static final String  _Saturation = bundle._res_Saturation;
  protected    String _res_ControlText = "ControlText";
  public static final String  _ControlText = bundle._res_ControlText;
  protected    String _res_RecordId = "Record {0} of {1}";
  public static final String  _RecordId = bundle._res_RecordId;
  protected    String _res_ItalicMnemonic = "i";
  public static final String  _ItalicMnemonic = bundle._res_ItalicMnemonic;
  protected    String _res_DeleteColumn = "Delete Column";
  public static final String  _DeleteColumn = bundle._res_DeleteColumn;
  protected    String _res_Details = "Details";
  public static final String  _Details = bundle._res_Details;
  protected    String _res_OK = "OK";
  public static final String  _OK = bundle._res_OK;
  protected    String _res_DeleteRow = "Delete Row";
  public static final String  _DeleteRow = bundle._res_DeleteRow;
  protected    String _res_PickFont = "Font...";
  public static final String  _PickFont = bundle._res_PickFont;
  protected    String _res_LightGray = "LightGray";
  public static final String  _LightGray = bundle._res_LightGray;
  protected    String _res_White = "White";
  public static final String  _White = bundle._res_White;
  protected    String _res_PickBackground = "Background...";
  public static final String  _PickBackground = bundle._res_PickBackground;
  protected    String _res_ControlHighlight = "ControlHighlight";
  public static final String  _ControlHighlight = bundle._res_ControlHighlight;
  protected    String _res_Yellow = "Yellow";
  public static final String  _Yellow = bundle._res_Yellow;
  protected    String _res_BGColorCaption = "Select background color";
  public static final String  _BGColorCaption = bundle._res_BGColorCaption;
  protected    String _res_NoFrame = "Frame property must be set before showing dialog.";
  public static final String  _NoFrame = bundle._res_NoFrame;
  protected    String _res_Previous = "Previous";
  public static final String  _Previous = bundle._res_Previous;
  protected    String _res_Cyan = "Cyan";
  public static final String  _Cyan = bundle._res_Cyan;
  protected    String _res_Window = "Window";
  public static final String  _Window = bundle._res_Window;
  protected    String _res_CustomColorTag = "<custom>";
  public static final String  _CustomColorTag = bundle._res_CustomColorTag;
  protected    String _res_AlignBottom = "Bottom";
  public static final String  _AlignBottom = bundle._res_AlignBottom;
  protected    String _res_Sample = "Selected color:";
  public static final String  _Sample = bundle._res_Sample;
  protected    String _res_BoldMnemonic = "b";
  public static final String  _BoldMnemonic = bundle._res_BoldMnemonic;
  protected    String _res_Menu = "Menu";
  public static final String  _Menu = bundle._res_Menu;
  protected    String _res_WindowText = "WindowText";
  public static final String  _WindowText = bundle._res_WindowText;
  protected    String _res_No1 = "No";
  public static final String  _No1 = bundle._res_No1;
  protected    String _res_Bold = "Bold";
  public static final String  _Bold = bundle._res_Bold;
  protected    String _res_Gray = "Gray";
  public static final String  _Gray = bundle._res_Gray;
  protected    String _res_ActiveCaptionText = "ActiveCaptionText";
  public static final String  _ActiveCaptionText = bundle._res_ActiveCaptionText;
  protected    String _res_Caption = "Caption...";
  public static final String  _Caption = bundle._res_Caption;
  protected    String _res_InactiveCaptionBorder = "InactiveCaptionBorder";
  public static final String  _InactiveCaptionBorder = bundle._res_InactiveCaptionBorder;
  protected    String _res_FontCaption = "Select font";
  public static final String  _FontCaption = bundle._res_FontCaption;
  protected    String _res_Text = "Text";
  public static final String  _Text = bundle._res_Text;
  protected    String _res_Alignment = "Alignment";
  public static final String  _Alignment = bundle._res_Alignment;
  protected    String _res_BlueLabel = "Blue:";
  public static final String  _BlueLabel = bundle._res_BlueLabel;
  protected    String _res_InsertColumn = "Insert Column";
  public static final String  _InsertColumn = bundle._res_InsertColumn;
  protected    String _res_InvalidButtonType = "Invalid button type : {0}";
  public static final String  _InvalidButtonType = bundle._res_InvalidButtonType;
  protected    String _res_DataEntryIncomplete = "Data entry incomplete";
  public static final String  _DataEntryIncomplete = bundle._res_DataEntryIncomplete;
  protected    String _res_HighlightText = "HighlightText";
  public static final String  _HighlightText = bundle._res_HighlightText;
  protected    String _res_Apply = "Apply";
  public static final String  _Apply = bundle._res_Apply;
  protected    String _res_CustomColorGroupBox = " Custom color settings: ";
  public static final String  _CustomColorGroupBox = bundle._res_CustomColorGroupBox;
  protected    String _res_Blue = "Blue";
  public static final String  _Blue = bundle._res_Blue;
  protected    String _res_InsertRow = "Insert Row";
  public static final String  _InsertRow = bundle._res_InsertRow;
  protected    String _res_UserName = "User Name";
  public static final String  _UserName = bundle._res_UserName;
  protected    String _res_DarkGray = "DarkGray";
  public static final String  _DarkGray = bundle._res_DarkGray;
  protected    String _res_CancelRow = "Cancel Row Changes";
  public static final String  _CancelRow = bundle._res_CancelRow;
  protected    String _res_Scrollbar = "Scrollbar";
  public static final String  _Scrollbar = bundle._res_Scrollbar;
  protected    String _res_RedLabel = "Red:";
  public static final String  _RedLabel = bundle._res_RedLabel;
  protected    String _res_ControlDkShadow = "ControlDkShadow";
  public static final String  _ControlDkShadow = bundle._res_ControlDkShadow;
  protected    String _res_Post = "Post";
  public static final String  _Post = bundle._res_Post;
  protected    String _res_StandardColors = "Standard colors:";
  public static final String  _StandardColors = bundle._res_StandardColors;
  protected    String _res_AlignMiddle = "Middle";
  public static final String  _AlignMiddle = bundle._res_AlignMiddle;
  protected    String _res_AlignCenter = "Center";
  public static final String  _AlignCenter = bundle._res_AlignCenter;
  protected    String _res_GreenLabel = "Green:";
  public static final String  _GreenLabel = bundle._res_GreenLabel;
  protected    String _res_Size = "Size";
  public static final String  _Size = bundle._res_Size;
  protected    String _res_InfoText = "InfoText";
  public static final String  _InfoText = bundle._res_InfoText;
  protected    String _res_Orange = "Orange";
  public static final String  _Orange = bundle._res_Orange;
  protected    String _res_InactiveCaption = "InactiveCaption";
  public static final String  _InactiveCaption = bundle._res_InactiveCaption;
  protected    String _res_Cancel1 = "Cancel";
  public static final String  _Cancel1 = bundle._res_Cancel1;
  protected    String _res_Pink = "Pink";
  public static final String  _Pink = bundle._res_Pink;
  protected    String _res_Green = "Green";
  public static final String  _Green = bundle._res_Green;
  protected    String _res_ActiveCaptionBorder = "ActiveCaptionBorder";
  public static final String  _ActiveCaptionBorder = bundle._res_ActiveCaptionBorder;
  protected    String _res_Done = "Done";
  public static final String  _Done = bundle._res_Done;
  protected    String _res_Password = "Password";
  public static final String  _Password = bundle._res_Password;
  protected    String _res_PickForeground = "Foreground...";
  public static final String  _PickForeground = bundle._res_PickForeground;
  protected    String _res_FGColorCaption = "Select foreground color";
  public static final String  _FGColorCaption = bundle._res_FGColorCaption;
  protected    String _res_ItemsAndDataSet = "Cannot set items property when control is bound to a DataSet.  You must clear the DataSet property first.";
  public static final String  _ItemsAndDataSet = bundle._res_ItemsAndDataSet;
  protected    String _res_AlignHStretch = "HStretch";
  public static final String  _AlignHStretch = bundle._res_AlignHStretch;
  protected    String _res_Prior = "Prior";
  public static final String  _Prior = bundle._res_Prior;
  protected    String _res_CaptionCaption = "Enter column caption";
  public static final String  _CaptionCaption = bundle._res_CaptionCaption;
  protected    String _res_ControlLtHighlight = "ControlLtHighlight";
  public static final String  _ControlLtHighlight = bundle._res_ControlLtHighlight;
  protected    String _res_Column = "Column {0}";
  public static final String  _Column = bundle._res_Column;
  protected    String _res_Desktop = "Desktop";
  public static final String  _Desktop = bundle._res_Desktop;
  protected    String _res_Next = "Next";
  public static final String  _Next = bundle._res_Next;
  protected    String _res_AlignLeft = "Left";
  public static final String  _AlignLeft = bundle._res_AlignLeft;
  protected    String _res_NextButton = "Next";
  public static final String  _NextButton = bundle._res_NextButton;
  protected    String _res_AlignRight = "Right";
  public static final String  _AlignRight = bundle._res_AlignRight;
  protected    String _res_Magenta = "Magenta";
  public static final String  _Magenta = bundle._res_Magenta;
  protected    String _res_Red = "Red";
  public static final String  _Red = bundle._res_Red;
  protected    String _res_EmptyDataSet = "(empty dataset) Use <Insert> to insert new row.";
  public static final String  _EmptyDataSet = bundle._res_EmptyDataSet;
  protected    String _res_Control = "Control";
  public static final String  _Control = bundle._res_Control;
  protected    String _res_WindowBorder = "WindowBorder";
  public static final String  _WindowBorder = bundle._res_WindowBorder;
  protected    String _res_RecursiveModel = "Cannot set model property to the component itself.";
  public static final String  _RecursiveModel = bundle._res_RecursiveModel;
  protected    String _res_Refresh = "Refresh";
  public static final String  _Refresh = bundle._res_Refresh;
//==========================================//

  public static String findString(String id) {
    try {
      return (String)Res.class.getDeclaredField("_" + id).get(null);
    } catch (Exception any) {
      return null;
    }
  }
}
