// DO NOT EDIT THIS FILE
// Copyright (c) 2005, Borland Software Corporation. All Rights Reserved.
// version 3

package com.borland.jbcl.view;

public class Res extends java.util.ResourceBundle {

  protected Object handleGetObject(String key) { return null; }
  public java.util.Enumeration getKeys()       { return null; }

  private static final Res bundle = getBundle();

  private static Res getBundle() {
    try {
      return (Res)getBundle("com.borland.jbcl.view.Res");
    } catch (Exception e) {
      return new Res();
    }
  }

//------------------------------------------//
  protected    String _res_ColumnName = "Column {0}";
  public static final String  _ColumnName = bundle._res_ColumnName;
  protected    String _res_SelectImageFile = "Select an image file to load";
  public static final String  _SelectImageFile = bundle._res_SelectImageFile;
  protected    String _res_BadHAlignment = "Bad horizontal alignment: {0}";
  public static final String  _BadHAlignment = bundle._res_BadHAlignment;
  protected    String _res_NullRectangles = "firstRect and secondRect must be constructed Rectangle objects";
  public static final String  _NullRectangles = bundle._res_NullRectangles;
  protected    String _res_Ellipsis = "...";
  public static final String  _Ellipsis = bundle._res_Ellipsis;
  protected    String _res_IllegalSubfocus = "Illegal subfocus value (out of range).";
  public static final String  _IllegalSubfocus = bundle._res_IllegalSubfocus;
  protected    String _res_CantResetImageStream = "Stream does not support reset";
  public static final String  _CantResetImageStream = bundle._res_CantResetImageStream;
  protected    String _res_BadVAlignment = "Bad vertical alignment: {0}";
  public static final String  _BadVAlignment = bundle._res_BadVAlignment;
  protected    String _res_Column = "Column {0}";
  public static final String  _Column = bundle._res_Column;
  protected    String _res_NullData = "(null)";
  public static final String  _NullData = bundle._res_NullData;
  protected    String _res_EditorCannotPost = "ItemEditor cannot post current value";
  public static final String  _EditorCannotPost = bundle._res_EditorCannotPost;
  protected    String _res_FileDialogNoFrame = "Can't use FileDialog without a frame";
  public static final String  _FileDialogNoFrame = bundle._res_FileDialogNoFrame;
//==========================================//

  public static String findString(String id) {
    try {
      return (String)Res.class.getDeclaredField("_" + id).get(null);
    } catch (Exception any) {
      return null;
    }
  }
}
