// DO NOT EDIT THIS FILE
// Copyright (c) 2005, Borland Software Corporation. All Rights Reserved.
// version 3

package com.borland.jbcl.view;

public class Res_de extends Res {
  public Res_de() {
    _res_ColumnName = "Spalte {0}";
    _res_SelectImageFile = "Grafikdatei ausw\u00e4hlen, die geladen werden soll";
    _res_BadHAlignment = "Ung\u00fcltige horizontale Ausrichtung: {0}";
    _res_NullRectangles = "firstRect und secondRect m\u00fcssen konstruierte Rectangle-Objekte sein";
    _res_Ellipsis = "...";
    _res_IllegalSubfocus = "Ung\u00fcltiger Wert f\u00fcr Subfokus (au\u00dferhalb des g\u00fcltigen Bereichs)";
    _res_CantResetImageStream = "Der Datenstrom unterst\u00fctzt kein Zur\u00fccksetzen";
    _res_BadVAlignment = "Ung\u00fcltige vertikale Ausrichtung: {0}";
    _res_Column = "Spalte {0}";
    _res_NullData = "(null)";
    _res_EditorCannotPost = "ItemEditor kann den aktuellen Wert nicht speichern";
    _res_FileDialogNoFrame = "Ohne Frame kann FileDialog nicht verwendet werden";
  }
}
