// DO NOT EDIT THIS FILE
// Copyright (c) 2005, Borland Software Corporation. All Rights Reserved.
// version 3

package com.borland.jbcl.editors;

public class Res extends java.util.ResourceBundle {

  protected Object handleGetObject(String key) { return null; }
  public java.util.Enumeration getKeys()       { return null; }

  private static final Res bundle = getBundle();

  private static Res getBundle() {
    try {
      return (Res)getBundle("com.borland.jbcl.editors.Res");
    } catch (Exception e) {
      return new Res();
    }
  }

//------------------------------------------//
  protected    String _res_AddColumn = "Add Column";
  public static final String  _AddColumn = bundle._res_AddColumn;
  protected    String _res_UNKNOWN = "Unknown";
  public static final String  _UNKNOWN = bundle._res_UNKNOWN;
  protected    String _res_AGGREGATE = "aggregated";
  public static final String  _AGGREGATE = bundle._res_AGGREGATE;
  protected    String _res_Pluses = "Pluses";
  public static final String  _Pluses = bundle._res_Pluses;
  protected    String _res_PosSlopeLine = "PosSlopeLine";
  public static final String  _PosSlopeLine = bundle._res_PosSlopeLine;
  protected    String _res_Arrows = "Arrows";
  public static final String  _Arrows = bundle._res_Arrows;
  protected    String _res_GridDirections = "Enter grid items.  Use buttons to insert/remove rows and columns.";
  public static final String  _GridDirections = bundle._res_GridDirections;
  protected    String _res_CenterVStretch = "Center+VStretch";
  public static final String  _CenterVStretch = bundle._res_CenterVStretch;
  protected    String _res_Save2 = "Save";
  public static final String  _Save2 = bundle._res_Save2;
  protected    String _res_Left = "Left";
  public static final String  _Left = bundle._res_Left;
  protected    String _res_AddRow = "Add Row";
  public static final String  _AddRow = bundle._res_AddRow;
  protected    String _res_HStretchVStretch = "HStretch+VStretch";
  public static final String  _HStretchVStretch = bundle._res_HStretchVStretch;
  protected    String _res_Center = "Center";
  public static final String  _Center = bundle._res_Center;
  protected    String _res_RightBottom = "Right+Bottom";
  public static final String  _RightBottom = bundle._res_RightBottom;
  protected    String _res_ENCODED = "Encoded";
  public static final String  _ENCODED = bundle._res_ENCODED;
  protected    String _res_MoveDown = "Move Down";
  public static final String  _MoveDown = bundle._res_MoveDown;
  protected    String _res_NewChild = "New Child";
  public static final String  _NewChild = bundle._res_NewChild;
  protected    String _res_NO_CALC = "not calculated";
  public static final String  _NO_CALC = bundle._res_NO_CALC;
  protected    String _res_TextAndImage = "TextAndImage";
  public static final String  _TextAndImage = bundle._res_TextAndImage;
  protected    String _res_Rectangle = "Rectangle";
  public static final String  _Rectangle = bundle._res_Rectangle;
  protected    String _res_SBP_AsNeeded = "AsNeeded";
  public static final String  _SBP_AsNeeded = bundle._res_SBP_AsNeeded;
  protected    String _res_MoveUp = "Move Up";
  public static final String  _MoveUp = bundle._res_MoveUp;
  protected    String _res_NegSlopeLine = "NegSlopeLine";
  public static final String  _NegSlopeLine = bundle._res_NegSlopeLine;
  protected    String _res_Square = "Square";
  public static final String  _Square = bundle._res_Square;
  protected    String _res_SERIALIZABLE = "Serializable";
  public static final String  _SERIALIZABLE = bundle._res_SERIALIZABLE;
  protected    String _res_ASCII = "Ascii";
  public static final String  _ASCII = bundle._res_ASCII;
  protected    String _res_CenterBottom = "Center+Bottom";
  public static final String  _CenterBottom = bundle._res_CenterBottom;
  protected    String _res_TextOnly = "TextOnly";
  public static final String  _TextOnly = bundle._res_TextOnly;
  protected    String _res_RemoveNode = "Remove";
  public static final String  _RemoveNode = bundle._res_RemoveNode;
  protected    String _res_LeftVStretch = "Left+VStretch";
  public static final String  _LeftVStretch = bundle._res_LeftVStretch;
  protected    String _res_CenterTop = "Center+Top";
  public static final String  _CenterTop = bundle._res_CenterTop;
  protected    String _res_Ok = "OK";
  public static final String  _Ok = bundle._res_Ok;
  protected    String _res_Unassigned = "Unassigned";
  public static final String  _Unassigned = bundle._res_Unassigned;
  protected    String _res_LeftMiddle = "Left+Middle";
  public static final String  _LeftMiddle = bundle._res_LeftMiddle;
  protected    String _res_RightVStretch = "Right+VStretch";
  public static final String  _RightVStretch = bundle._res_RightVStretch;
  protected    String _res_ORACLE = "Oracle";
  public static final String  _ORACLE = bundle._res_ORACLE;
  protected    String _res_FileChooserTitle = "Select File";
  public static final String  _FileChooserTitle = bundle._res_FileChooserTitle;
  protected    String _res_Remove = "Remove";
  public static final String  _Remove = bundle._res_Remove;
  protected    String _res_LOOKUP = "lookup";
  public static final String  _LOOKUP = bundle._res_LOOKUP;
  protected    String _res_FileNameLabel = "File name:";
  public static final String  _FileNameLabel = bundle._res_FileNameLabel;
  protected    String _res_Add = "Add";
  public static final String  _Add = bundle._res_Add;
  protected    String _res_VertLine = "VertLine";
  public static final String  _VertLine = bundle._res_VertLine;
  protected    String _res_Clear = "Clear";
  public static final String  _Clear = bundle._res_Clear;
  protected    String _res_Right = "Right";
  public static final String  _Right = bundle._res_Right;
  protected    String _res_Raised = "Raised";
  public static final String  _Raised = bundle._res_Raised;
  protected    String _res_HStretchBottom = "HStretch+Bottom";
  public static final String  _HStretchBottom = bundle._res_HStretchBottom;
  protected    String _res_READ_COMMITTED = "Read committed";
  public static final String  _READ_COMMITTED = bundle._res_READ_COMMITTED;
  protected    String _res_SBP_Always = "Always";
  public static final String  _SBP_Always = bundle._res_SBP_Always;
  protected    String _res_Horizontal = "Horizontal";
  public static final String  _Horizontal = bundle._res_Horizontal;
  protected    String _res_Yes2 = "Yes";
  public static final String  _Yes2 = bundle._res_Yes2;
  protected    String _res_LeftTop = "Left+Top";
  public static final String  _LeftTop = bundle._res_LeftTop;
  protected    String _res_NONE = "None";
  public static final String  _NONE = bundle._res_NONE;
  protected    String _res_RightMiddle = "Right+Middle";
  public static final String  _RightMiddle = bundle._res_RightMiddle;
  protected    String _res_HStretchMiddle = "HStretch+Middle";
  public static final String  _HStretchMiddle = bundle._res_HStretchMiddle;
  protected    String _res_YesNo = "YesNo";
  public static final String  _YesNo = bundle._res_YesNo;
  protected    String _res_LOCALE_DEFAULT = "<default>";
  public static final String  _LOCALE_DEFAULT = bundle._res_LOCALE_DEFAULT;
  protected    String _res_OkCancel = "OkCancel";
  public static final String  _OkCancel = bundle._res_OkCancel;
  protected    String _res_ImageOnly = "ImageOnly";
  public static final String  _ImageOnly = bundle._res_ImageOnly;
  protected    String _res_DirectoryLabelText = "Directory name:";
  public static final String  _DirectoryLabelText = bundle._res_DirectoryLabelText;
  protected    String _res_INTERBASE = "Interbase";
  public static final String  _INTERBASE = bundle._res_INTERBASE;
  protected    String _res_Vertical = "Vertical";
  public static final String  _Vertical = bundle._res_Vertical;
  protected    String _res_CenterMiddle = "Center+Middle";
  public static final String  _CenterMiddle = bundle._res_CenterMiddle;
  protected    String _res_REPEATABLE_READ = "Repeatable read";
  public static final String  _REPEATABLE_READ = bundle._res_REPEATABLE_READ;
  protected    String _res_ItemX = "Item {0}";
  public static final String  _ItemX = bundle._res_ItemX;
  protected    String _res_Cancel2 = "Cancel";
  public static final String  _Cancel2 = bundle._res_Cancel2;
  protected    String _res_RoundSquare = "RoundSquare";
  public static final String  _RoundSquare = bundle._res_RoundSquare;
  protected    String _res_HorzLine = "HorzLine";
  public static final String  _HorzLine = bundle._res_HorzLine;
  protected    String _res_MoveNodeDown = "Move Down";
  public static final String  _MoveNodeDown = bundle._res_MoveNodeDown;
  protected    String _res_YesNoCancel = "YesNoCancel";
  public static final String  _YesNoCancel = bundle._res_YesNoCancel;
  protected    String _res_MoveNodeUp = "Move Up";
  public static final String  _MoveNodeUp = bundle._res_MoveNodeUp;
  protected    String _res_AddChild = "Add Child";
  public static final String  _AddChild = bundle._res_AddChild;
  protected    String _res_Load = "Load";
  public static final String  _Load = bundle._res_Load;
  protected    String _res_No2 = "No";
  public static final String  _No2 = bundle._res_No2;
  protected    String _res_WhereKeyOnly = "Key columns only";
  public static final String  _WhereKeyOnly = bundle._res_WhereKeyOnly;
  protected    String _res_RightTop = "Right+Top";
  public static final String  _RightTop = bundle._res_RightTop;
  protected    String _res_Lowered = "Lowered";
  public static final String  _Lowered = bundle._res_Lowered;
  protected    String _res_RemoveRow = "Remove Row";
  public static final String  _RemoveRow = bundle._res_RemoveRow;
  protected    String _res_LeftBottom = "Left+Bottom";
  public static final String  _LeftBottom = bundle._res_LeftBottom;
  protected    String _res_CALC = "calculated";
  public static final String  _CALC = bundle._res_CALC;
  protected    String _res_RemoveColumn = "Remove Column";
  public static final String  _RemoveColumn = bundle._res_RemoveColumn;
  protected    String _res_READ_UNCOMMITTED = "Read uncommitted";
  public static final String  _READ_UNCOMMITTED = bundle._res_READ_UNCOMMITTED;
  protected    String _res_HStretchTop = "HStretch+Top";
  public static final String  _HStretchTop = bundle._res_HStretchTop;
  protected    String _res_Circle = "Circle";
  public static final String  _Circle = bundle._res_Circle;
  protected    String _res_Ellipse = "Ellipse";
  public static final String  _Ellipse = bundle._res_Ellipse;
  protected    String _res_WhereChanged = "Changed columns";
  public static final String  _WhereChanged = bundle._res_WhereChanged;
  protected    String _res_WhereAll = "All columns";
  public static final String  _WhereAll = bundle._res_WhereAll;
  protected    String _res_SBP_Never = "Never";
  public static final String  _SBP_Never = bundle._res_SBP_Never;
  protected    String _res_Flat = "Flat";
  public static final String  _Flat = bundle._res_Flat;
  protected    String _res_RoundRect = "RoundRect";
  public static final String  _RoundRect = bundle._res_RoundRect;
//==========================================//

  public static String findString(String id) {
    try {
      return (String)Res.class.getDeclaredField("_" + id).get(null);
    } catch (Exception any) {
      return null;
    }
  }
}
