// DO NOT EDIT THIS FILE
// Copyright (c) 2005, Borland Software Corporation. All Rights Reserved.
// version 3

package com.borland.jbcl.editors;

public class Res_de extends Res {
  public Res_de() {
    _res_AddColumn = "Spalte hinzuf\u00fcgen";
    _res_UNKNOWN = "Unbekannt";
    _res_AGGREGATE = "Aggregiert";
    _res_Pluses = "Plus";
    _res_PosSlopeLine = "PosSlopeLine";
    _res_Arrows = "Pfeile";
    _res_GridDirections = "Tabelleneintr\u00e4ge eingeben. Mit den Schaltern werden Zeilen und Spalten eingef\u00fcgt/entfernt.";
    _res_CenterVStretch = "Zentriert+VDehnen";
    _res_Save2 = "Speichern";
    _res_Left = "Links";
    _res_AddRow = "Zeile hinzuf\u00fcgen";
    _res_HStretchVStretch = "HDehnen+VDehnen";
    _res_Center = "Zentriert";
    _res_RightBottom = "Rechts+Unten";
    _res_ENCODED = "Codiert";
    _res_MoveDown = "Nach unten";
    _res_NewChild = "Neues untergeordnetes Element";
    _res_NO_CALC = "Nicht berechnet";
    _res_TextAndImage = "TextUndGrafik";
    _res_Rectangle = "Rechteck";
    _res_SBP_AsNeeded = "Wie ben\u00f6tigt";
    _res_MoveUp = "Nach oben";
    _res_NegSlopeLine = "NegSlopeLine";
    _res_Square = "Quadrat";
    _res_SERIALIZABLE = "Serializable";
    _res_ASCII = "Ascii";
    _res_CenterBottom = "Zentriert+Unten";
    _res_TextOnly = "NurText";
    _res_RemoveNode = "Entfernen";
    _res_LeftVStretch = "Links+VDehnen";
    _res_CenterTop = "Zentriert+Oben";
    _res_Ok = "OK";
    _res_Unassigned = "Nicht zugewiesen";
    _res_LeftMiddle = "Links+Mitte";
    _res_RightVStretch = "Rechts+VDehnen";
    _res_ORACLE = "Oracle";
    _res_FileChooserTitle = "Datei w\u00e4hlen";
    _res_Remove = "Entfernen";
    _res_LOOKUP = "Nachschlagen";
    _res_FileNameLabel = "Dateiname:";
    _res_Add = "Hinzuf\u00fcgen";
    _res_VertLine = "VertLinie";
    _res_Clear = "L\u00f6schen";
    _res_Right = "Rechts";
    _res_Raised = "Erh\u00f6ht";
    _res_HStretchBottom = "HDehnen+Unten";
    _res_READ_COMMITTED = "Read committed";
    _res_SBP_Always = "Immer";
    _res_Horizontal = "Horizontal";
    _res_Yes2 = "Ja";
    _res_LeftTop = "Links+Oben";
    _res_NONE = "ohne";
    _res_RightMiddle = "Rechts+Mitte";
    _res_HStretchMiddle = "HDehnen+Mitte";
    _res_YesNo = "YesNo";
    _res_LOCALE_DEFAULT = "<vorgabe>";
    _res_OkCancel = "OkCancel";
    _res_ImageOnly = "ImageOnly";
    _res_DirectoryLabelText = "Verzeichnisname:";
    _res_INTERBASE = "Interbase";
    _res_Vertical = "Vertikal";
    _res_CenterMiddle = "Zentriert+Mitte";
    _res_REPEATABLE_READ = "Repeatable read";
    _res_ItemX = "Eintrag {0}";
    _res_Cancel2 = "Abbrechen";
    _res_RoundSquare = "Quadrat abgerundet";
    _res_HorzLine = "HorzLinie";
    _res_MoveNodeDown = "Nach unten";
    _res_YesNoCancel = "YesNoCancel";
    _res_MoveNodeUp = "Nach oben";
    _res_AddChild = "Untergeordnetes Element hinzuf\u00fcgen";
    _res_Load = "\u00d6ffnen";
    _res_No2 = "Nein";
    _res_WhereKeyOnly = "Nur Schl\u00fcsselspalten";
    _res_RightTop = "Rechts+Oben";
    _res_Lowered = "Abgesenkt";
    _res_RemoveRow = "Zeile entfernen";
    _res_LeftBottom = "Links+Unten";
    _res_CALC = "Berechnet";
    _res_RemoveColumn = "Spalte entfernen";
    _res_READ_UNCOMMITTED = "Read uncommitted";
    _res_HStretchTop = "HDehnen+Oben";
    _res_Circle = "Kreis";
    _res_Ellipse = "Ellipse";
    _res_WhereChanged = "Ge\u00e4nderte Spalten";
    _res_WhereAll = "Alle Spalten";
    _res_SBP_Never = "Nie";
    _res_Flat = "Flat";
    _res_RoundRect = "Rechteck abgerundet";
  }
}
