// DO NOT EDIT THIS FILE
// Copyright (c) 2005, Borland Software Corporation. All Rights Reserved.
// version 3

package com.borland.jbcl.sql.monitor;

public class Res extends java.util.ResourceBundle {

  protected Object handleGetObject(String key) { return null; }
  public java.util.Enumeration getKeys()       { return null; }

  private static final Res bundle = getBundle();

  private static Res getBundle() {
    try {
      return (Res)getBundle("com.borland.jbcl.sql.monitor.Res");
    } catch (Exception e) {
      return new Res();
    }
  }

//------------------------------------------//
  protected    String _res_OK = "OK";
  public static final String  _OK = bundle._res_OK;
  protected    String _res_SaveMnemonic = "S";
  public static final String  _SaveMnemonic = bundle._res_SaveMnemonic;
  protected    String _res_Clear = "Clear log";
  public static final String  _Clear = bundle._res_Clear;
  protected    String _res_JDBC_trace = "JDBC trace";
  public static final String  _JDBC_trace = bundle._res_JDBC_trace;
  protected    String _res_Bridge = "Bridge";
  public static final String  _Bridge = bundle._res_Bridge;
  protected    String _res_Save = "Save to File";
  public static final String  _Save = bundle._res_Save;
  protected    String _res_ClearMnemonic = "c";
  public static final String  _ClearMnemonic = bundle._res_ClearMnemonic;
  protected    String _res_server = "server:";
  public static final String  _server = bundle._res_server;
  protected    String _res_MonitorTitle = "JDBC Monitor Dialog";
  public static final String  _MonitorTitle = bundle._res_MonitorTitle;
  protected    String _res_Broker = "Broker";
  public static final String  _Broker = bundle._res_Broker;
  protected    String _res_EnableMnemonic = "E";
  public static final String  _EnableMnemonic = bundle._res_EnableMnemonic;
  protected    String _res_Enable = "Enable log output";
  public static final String  _Enable = bundle._res_Enable;
//==========================================//

  public static String findString(String id) {
    try {
      return (String)Res.class.getDeclaredField("_" + id).get(null);
    } catch (Exception any) {
      return null;
    }
  }
}
