// DO NOT EDIT THIS FILE
// Copyright (c) 2005, Borland Software Corporation. All Rights Reserved.
// version 3

package com.borland.jbcl.sql.monitor;

public class Res_de extends Res {
  public Res_de() {
    _res_OK = "OK";
    _res_SaveMnemonic = "S";
    _res_Clear = "Protokoll l\u00f6schen";
    _res_Save = "In Datei speichern";
    _res_ClearMnemonic = "l";
    _res_MonitorTitle = "Dialog JDBC-Monitor";
    _res_EnableMnemonic = "k";
    _res_Enable = "Protokollierung aktivieren";
  }
}
