// DO NOT EDIT THIS FILE
// Copyright (c) 2005, Borland Software Corporation. All Rights Reserved.
// version 3

package com.borland.dbswing.editors;

public class Res_de extends Res {
  public Res_de() {
    _res_BI_German = "Deutsch";
    _res_BI_Spanish = "Spanisch";
    _res_BI_Italian = "Italienisch";
    _res_BI_Greek = "Griechisch";
    _res_BI_Chinese_China = "Chinesisch (China)";
    _res_BI_Russian = "Russisch";
    _res_BI_Turkish = "T\u00fcrkisch";
    _res_BI_Korean = "Koreanisch";
    _res_BI_French = "Franz\u00f6sisch";
    _res_BI_Chinese_Taiwan = "Chinesisch (Taiwan)";
    _res_BI_default = "<vorgabe>";
    _res_BI_Croatian = "Kroatisch";
    _res_BI_Norwegian = "Norwegisch";
  }
}
