// DO NOT EDIT THIS FILE
// Copyright (c) 2005, Borland Software Corporation. All Rights Reserved.
// version 3

package com.borland.jbcl.util;

public class Res extends java.util.ResourceBundle {

  protected Object handleGetObject(String key) { return null; }
  public java.util.Enumeration getKeys()       { return null; }

  private static final Res bundle = getBundle();

  private static Res getBundle() {
    try {
      return (Res)getBundle("com.borland.jbcl.util.Res");
    } catch (Exception e) {
      return new Res();
    }
  }

//------------------------------------------//
  protected    String _res_NotInRange = "ColorWheel increment must be in range (1-255)";
  public static final String  _NotInRange = bundle._res_NotInRange;
  protected    String _res_InvalidCycle = "Invalid ColorWheel cycle: ";
  public static final String  _InvalidCycle = bundle._res_InvalidCycle;
//==========================================//

  public static String findString(String id) {
    try {
      return (String)Res.class.getDeclaredField("_" + id).get(null);
    } catch (Exception any) {
      return null;
    }
  }
}
