// DO NOT EDIT THIS FILE
// Copyright (c) 2005, Borland Software Corporation. All Rights Reserved.
// version 3

package com.borland.jbcl.util;

public class Res_de extends Res {
  public Res_de() {
    _res_NotInRange = "Steigerungen von ColorWheel m\u00fcssen zwischen 1 und 255 liegen";
    _res_InvalidCycle = "Ung\u00fcltiger Zyklus f\u00fcr ColorWheel: ";
  }
}
